FROM ubuntu:16.04

MAINTAINER jiamingjxu@gmail.com

ENV LANG C.UTF-8

RUN mkdir -p /setupTesting

COPY . /setupTesting

WORKDIR /setupTesting

RUN apt-get update
	
RUN apt-get install -y python-pip libpq-dev python-dev

RUN apt-get install -y git

RUN pip install -U pytest

RUN pip install -r test_requirements.txt

RUN python setup.py build 

RUN python setup.py install

RUN python -m pytest tests/artifact_store_test.py
