#!/bin/bash

# Script that starts remote worker
# Usage:
#
#   studio-start-remote-worker --queue=<queue_name> [--image=<custom_docker_image] [--single-run]
# 
#   --queue argument specifies the name of the queue remote worker is listening to
#   --image optional argument specifies the docker image to be used. Image should have studio installed.
#           Default is peterzhokhoff/tfstudio
#           
#   --single-run optional argument specifies that docker container should not be restarted. 
#           By default, the container will be restarted after the job is done. 



docker_cmd=docker
docker_img=peterzhokhoff/tfstudio


while [[ $# -gt 0 ]] 
do 
    key="$1"
    case ${key%%=*} in 
            -q|--queue)
            queue_name="${1##*=}"
            ;;

            -i|--image)
            docker_img="${1##*=}"
            ;;

            -s|--single-run)
            single_run=1
            echo Single run mode
    esac
    shift
done

if [ -z $queue_name ]
then
        echo "Queue name not specified! Use --queue=<queue_name> argument" 
        exit 1
fi

echo "Docker image = $docker_img"
echo "Queue = $queue_name"

eval $docker_cmd
if [ $? != 0 ]; then
   echo "Docker not installed! Install docker."
   exit 1
fi

eval nvidia-smi
if [ $? == 0 ]; then
    eval nvidia-docker
    if [ $? == 0 ]; then
        docker_cmd=nvidia-docker
        bash_cmd=""
    else
        echo "Warning! nvidia-docker is not installed correctly, won't be able to use gpus"
    fi
fi

echo "docker_cmd = $docker_cmd"
if [ $docker_cmd == 'docker' ]; then
    bash_cmd="pip uninstall -y tensorflow-gpu tensorflow && pip install tensorflow &&"
fi

bash_cmd="$bash_cmd mkdir /workspace && cd workspace && studio-remote-worker --queue=$queue_name --verbose=debug --single-run"

: "${GOOGLE_APPLICATION_CREDENTIALS?Need to point GOOGLE_APPLICATION_CREDENTIALS to the google credentials file}"
: "${queue_name?Queue name is not specified (pass as a script argument}"

gac_path=${GOOGLE_APPLICATION_CREDENTIALS%/*}
gac_name=${GOOGLE_APPLICATION_CREDENTIALS##*/}

#bash_cmd="git clone $repo && \
#            cd studio && \
#            git checkout $branch && \
#            sudo pip install --upgrade pip && \
#            sudo pip install -e . --upgrade && \
#            mkdir /workspace && cd /workspace && \
#            studio-rworker --queue=$queue_name"


# loop until killed
while true
do
    echo $bash_cmd
    $docker_cmd pull $docker_img
    $docker_cmd run --rm \
            -v $HOME/.tfstudio/keys:/root/.tfstudio/keys \
            -v $gac_path:/creds \
            --pid=host \
            -e GOOGLE_APPLICATION_CREDENTIALS="/creds/$gac_name" \
            $docker_img \
        /bin/bash -c "$bash_cmd"
   if [ $single_run ];
   then
           exit 0
   fi
done

