#!/bin/bash


function parse_command {

    expected_command=$1
    shift
    cmd="studio"
    for w in $expected_command; do
        if [ "$w" = "$1" ]; then
            cmd="$cmd-$w"
            shift
        else
            echo "Unknown command $1"
            exit 1
        fi
    done

    echo $cmd $*
    eval $cmd $*
    exit $?
}



case $1 in
    run)
    parse_command "run" $*
    ;;

    ui)
    parse_command "ui" $*
    ;;  

    start)
    parse_command "start remote worker" $*
    ;;

    remote)
    parse_command "remote worker" $*
    ;;

    add)
    parse_command "add credentials" $*
    ;;

esac

echo "Unknown command $1"
exit 1



 
